name: markdownlint

on: [push, pull_request, workflow_dispatch]

jobs:
  markdownlint:
    name: Lint markdown files
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b
